import assert from "node:assert/strict";
import test from "node:test";
import vm from "node:vm";
import { tickPartChecklistScript } from "../../src/review-component.js";

test("actual checklist component renders review routes and exports durable inspection JSON", () => {
  const saved = new Map<string, string>(); let Component: any; let blobText = ""; let download = "";
  class Input { dataset: Record<string,string> = {}; checked = false; indeterminate = false; handlers: Record<string, () => void> = {}; addEventListener(name:string, fn:()=>void){this.handlers[name]=fn;} }
  class Root { html=""; activeElement:any; inputs: Input[]=[]; innerHTMLSet(value:string){this.html=value; this.inputs=[]; for(const match of value.matchAll(/<input[^>]+>/g)){const input=new Input(); input.checked=/ checked/.test(match[0]); for(const pair of match[0].matchAll(/data-([a-z-]+)="([^"]*)"/g)) input.dataset[pair[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=pair[2]; this.inputs.push(input);} } set innerHTML(v:string){this.innerHTMLSet(v)} get innerHTML(){return this.html} querySelector(){return new Input()} querySelectorAll(selector:string){ if(selector==='[data-p]') return this.inputs.filter(x=>x.dataset.p); if(selector==='[data-all]') return this.inputs.filter(x=>x.dataset.all); return []; } getElementById(){return undefined;} }
  class Element { shadowRoot:any; attrs=new Map<string,string>(); attachShadow(){return this.shadowRoot=new Root()} getAttribute(k:string){return this.attrs.get(k)??null} setAttribute(k:string,v:string){this.attrs.set(k,v)} dispatchEvent(){} get isConnected(){return true} }
  const context:any={ HTMLElement:Element, customElements:{get(){return undefined},define(_:string,c:any){Component=c}}, localStorage:{getItem:(k:string)=>saved.get(k)??null,setItem:(k:string,v:string)=>saved.set(k,v)}, window:{localStorage:{getItem:(k:string)=>saved.get(k)??null,setItem:(k:string,v:string)=>saved.set(k,v)},prompt:()=>"Sam"}, CustomEvent:class{constructor(_:string,public init:any){}}, Blob:class{constructor(parts:any[]){blobText=parts.join("")}}, URL:{createObjectURL:()=>"blob:x",revokeObjectURL(){}}, document:{createElement:()=>({click(){},set href(_:string){},set download(v:string){download=v}})}, setTimeout:(fn:()=>void)=>fn() };
  vm.runInNewContext(tickPartChecklistScript, context); const el=new Component(); el.setAttribute("storage-key","k"); el.setAttribute("submission-id","s"); el.setAttribute("item-id","i"); el.setAttribute("checkpoint-id","c"); el.setAttribute("subject-commit","sha"); el.setAttribute("data-checklist",JSON.stringify([{id:"t",label:"Target",parts:[{id:"p",label:"Inspect",reviewId:"p",action:{label:"Open",href:"report.html"}}]}])); el.connectedCallback();
  assert.match(el.shadowRoot.innerHTML,/Target/); assert.match(el.shadowRoot.innerHTML,/Inspect/); assert.match(el.shadowRoot.innerHTML,/href="report.html"/);
  const part=el.shadowRoot.querySelectorAll('[data-p]')[0]; part.checked=true; part.handlers.change(); el.export([{id:"p",reviewId:"p",_tick:"t"}]); const parsed=JSON.parse(blobText); assert.equal(parsed.inspected.p,true); assert.equal(parsed.subjectCommit,"sha"); assert.match(download,/inspection-/);
  const other=new Component(); other.setAttribute("storage-key","k"); other.setAttribute("submission-id","other"); other.setAttribute("checkpoint-id","c2"); other.setAttribute("data-checklist",JSON.stringify([{id:"legacy",label:"Legacy",parts:[]}])); other.connectedCallback(); const all=other.shadowRoot.querySelectorAll('[data-all]')[0]; all.checked=true; all.handlers.change(); assert.match(other.shadowRoot.innerHTML,/Legacy/);
});
